### ISSUE TITLE
Pretrain model link

### ISSUE THREAD

**Issue by Guuudeluck** [nwams/ClinicalBERT-Deep-Learning--Predicting-Hospital-Readmission-Using-Transformer#1]
Hi there,

The link for pretrain model at Kexin's Github is expired, and I am wondering if you happen to have a copy of it.

Thanks a lot!

**Comment by nwams** [comment]
Hi @Guuudeluck thanks for pointing that out! It's been such a while that I had to hunt down this link quickly. https://drive.google.com/drive/folders/1kH8nsBL5Ld3vmkguYGHycLayXTnA42XR?usp=sharing

I'm quite busy these days and I haven't had the chance to look through all the files thoroughly. Please let me know if this is what you're looking for?

Hope it helps!

**Comment by Guuudeluck** [comment]
Thanks! That's super helpful!
