### ISSUE TITLE
The link to download pretrained ClinicalBERT model  does not work

### ISSUE THREAD

**Issue by moeenm** [nwams/ClinicalBERT-Deep-Learning--Predicting-Hospital-Readmission-Using-Transformer#4]
Thank you for implementing ClinicalBERT on Transformer. It looks the google drive link you shared for the pre-trained model is no longer working. Could you please check it?

"You can use [this google link](https://drive.google.com/open?id=1t8L9w-r88Q5-sfC993x2Tjt1pu--A900) to download the pre-trained ClinicalBERT model along with the readmission task fine-tuned model weights."

**Comment by nwams** [comment]
Hi @moeenm you're welcome it's my pleasure. Please double check the article: https://medium.com/nwamaka-imasogie/clinicalbert-using-deep-learning-transformer-model-to-predict-hospital-readmission-c82ff0e4bb03

On my end, the link in the article is working.
